### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by davidcoble** [travisperson/chromecaster#1]
Hi. 

Read the readme.md  Followed the instructions.  :-)

Transcript:

coble@mars 15:16:58 /home/coble/work/chromecaster$ npm install -g chromecaster
npm http GET https://registry.npmjs.org/chromecaster

npm ERR! Error: failed to fetch from registry: chromecaster
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/coble/work/chromecaster/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-84-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "chromecaster"
npm ERR! cwd /home/coble/work/chromecaster
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: chromecaster
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/coble/work/chromecaster/npm-debug.log
npm not ok

coble@mars 15:22:05 /home/coble/work/chromecaster$ cat /home/coble/work/chromecaster/npm-debug.log
info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'chromecaster' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/coble/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose cache add [ 'chromecaster', null ]
silly cache add: name, spec, args [ undefined, 'chromecaster', [ 'chromecaster', null ] ]
verbose parsed url { pathname: 'chromecaster',
verbose parsed url   path: 'chromecaster',
verbose parsed url   href: 'chromecaster' }
verbose addNamed [ 'chromecaster', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'chromecaster', '', false ]
verbose raw, before any munging chromecaster
verbose url resolving [ 'https://registry.npmjs.org/', './chromecaster' ]
verbose url resolved https://registry.npmjs.org/chromecaster
http GET https://registry.npmjs.org/chromecaster
ERR! Error: failed to fetch from registry: chromecaster
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     http://bugs.debian.org/npm
ERR! or use
ERR!     reportbug --attach /home/coble/work/chromecaster/npm-debug.log npm
ERR! 
ERR! System Linux 3.2.0-84-generic-pae
ERR! command "node" "/usr/bin/npm" "install" "-g" "chromecaster"
ERR! cwd /home/coble/work/chromecaster
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: chromecaster
verbose exit [ 1, true ]

**Comment by travisperson** [comment]
This might not be your issue but you may want to update your node version and npm.

> info using npm@1.1.4
> info using node@v0.6.12

That is where I would start. The current version of npm is `2.6.0`.

**Comment by davidcoble** [comment]
Thanks, Travis.

I'll give that a try.

<removed photo numbers from email reply>

**Comment by davidcoble** [comment]
Hi Travis.  I got it running, but when I try to stream something, my tv
shows that something is inbound, but never starts playing.  Is there a
specific codec I should use?

I user Handbrake for transcoding https://handbrake.fr/  maybe there's a
specific preset you can recommend?

Dave Coble
C: 206.228.6835
H: 206.486.0946
